import React from 'react'
import { Header } from '../components/Header'
import FooterSouthsore from '../components/FooterSouthsore'
import NavbarSouthshore from '../components/NavBarSouthshore'

const References = () => {
    return (
        <>
            <div className="container">
                <Header />
                <NavbarSouthshore />
                <div id="_idContainer001" className="Basic-Text-Frame">
                    <p className="H1" lang="en-US"><span className="Bold">Introduction</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Setting the Stage: The Role of Communication in Healthcare</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="Ref ParaOverride-1" lang="en-US">Agarwal, R., Sands, D. Z., &amp; Schneider, J. D. (2010). Quantifying the economic impact of communication inefficiencies in U.S. hospitals. <span className="Italic">Journal of Healthcare Management, 55</span>(4), 265–282. <a href="https://doi.org/10.1097/00115514-201007000-00007"><span className="Hyperlink">https://doi.org/10.1097/00115514-201007000-00007</span></a></li>
                    </ol>
                    <p className="H2-copy" lang="en-US"><span className="Bold">ADDITIONAL RESOURCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">[Book] <span className="Italic">Communicate. Care. Cure. A Guide to Healthcare Communication, Third Edition,</span> edited by Alexander Thomas and Divya Alexander</li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 1</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">First Impressions Matter: Creating Memorable Experiences for Patients</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Rimondini, M., Mazzi, M. A., Busch, I. M., &amp; Bensing, J. (2019). You only have one chance for a first impression! Impact of patients’ first impression on the global quality assessment of doctors’ communication approach. <span className="Italic">Health Communication</span>, <span className="Italic">34</span>(12), 1413–1422. <a href="https://doi.org/10.1080/10410236.2018.1495159"><span className="Hyperlink">https://doi.org/10.1080/10410236.2018.1495159</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Agency for Healthcare Research and Quality. (2023). <span className="Italic">Improving healthcare safety by enhancing healthcare facility design. </span>AHRQ.<span className="Italic"> </span><a href="https://www.ahrq.gov/sites/default/files/wysiwyg/patient-safety/highlights/ps-project-highlights-hcfd-041825.pdf"><span className="Hyperlink">https://www.ahrq.gov/sites/default/files/wysiwyg/patient-safety/highlights/ps-project-highlights-hcfd-041825.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Agency for Healthcare Research and Quality. (2017, December). <span className="Italic">Transforming hospitals: Designing for safety and quality</span> [Video]. AHRQ. <a href="https://www.ahrq.gov/patient-safety/settings/hospital/resource/transform.html"><span className="Hyperlink">https://www.ahrq.gov/patient-safety/settings/hospital/resource/transform.html</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Hains, K. (2011). Communication essentials for good impressions. <span className="Italic">Community and Leadership Development</span>, 15. University of Kentucky.  <a href="https://uknowledge.uky.edu/leadership_development/15/"><span className="Hyperlink">https://uknowledge.uky.edu/leadership_development/15/</span></a> </li>
                        <li className="Ref ParaOverride-1" lang="en-US">Ackerman, J. M., Nocera, C. C., &amp; Bargh, J. A. (2010). Incidental haptic sensations influence social judgments and decisions. <span className="Italic">Science, 328</span>(5986), 1712–1715. <a href="https://doi.org/10.1126/science.1189993"><span className="Hyperlink">https://doi.org/10.1126/science.1189993</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Gladwell, M. (2005). <span className="Italic">Blink: The power of thinking without thinking</span>. Penguin.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Joly, H. (2023, October 26). <span className="Italic">How to connect employees to your company’s purpose. Harvard Business Review</span>. <a href="https://hbr.org/2023/10/how-to-connect-employees-to-your-companys-purpose"><span className="Hyperlink">https://hbr.org/2023/10/how-to-connect-employees-to-your-companys-purpose</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 2</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Listening with Undivided Attention: An Effective Prescription for Healing</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">International Listening Association. (1995) An ILA definition of listening. <span className="Italic">The Listening Post</span>, <span className="Italic">53</span>(1), 4–5.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Brownell, J. (2006). <span className="Italic">Listening: Attitudes, principles, and skills</span> (3rd ed.). Allyn &amp; Bacon.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Covey, S. R. (1989). <span className="Italic">The seven habits of highly effective people</span>. Free Press.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Athos, A. G., &amp; Gabarro, J. J. (1978). <span className="Italic">Interpersonal behavior: Communication and understanding in relationships</span> (Chapters 9 &amp; 10, illustrated ed.). Prentice-Hall.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Coyle, A. C., Yen, R. W., &amp; Elwyn, G. (2022). Interrupted opening statements in clinical encounters: A scoping review. <span className="Italic">Patient Education and Counseling, 105</span>(8), 2653–2663. <a href="https://doi.org/10.1016/j.pec.2022.03.026"><span className="Hyperlink">https://doi.org/10.1016/j.pec.2022.03.026</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 3</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Nonverbal Communication: Actions Speak Louder than Words</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Darwin, C. (1899). <span className="Italic">The expression of the emotions in man and animals</span>. D. Appleton &amp; Co.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Roter, D. L., Frankel, R. M., Hall, J. A., &amp; Sluyter, D. (2006). The expression of emotion through nonverbal behavior in medical visits. Mechanisms and outcomes.&#160;<span className="Italic">Journal of General Internal Medicine</span>,&#160;<span className="Italic">21</span>(Suppl 1), S28–S34. <a href="https://doi.org/10.1111/j.1525-1497.2006.00306.x"><span className="Hyperlink">https://doi.org/10.1111/j.1525-1497.2006.00306.x</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Ambady, N., Koo, J., Rosenthal, R., &amp; Winograd, C. H. (2002). Physical therapists’ nonverbal communication predicts geriatric patients’ health outcomes. <span className="Italic">Psychology and Aging, 17</span>(3), 443–452. <a href="https://doi.org/10.1037/0882-7974.17.3.443"><span className="Hyperlink">https://doi.org/10.1037/0882-7974.17.3.443</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Rosenthal, R., Blanck, P. D., &amp; Vannicelli, M. (1984). Speaking to and about patients: Predicting therapists’ tone of voice. <span className="Italic">Journal of Consulting and Clinical Psychology, 52</span>(4), 679–686. <a href="https://doi.org/10.1037/0022-006X.52.4.679"><span className="Hyperlink">https://doi.org/10.1037/0022-006X.52.4.679</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Milmoe, S., Rosenthal, R., Blane, H. T., Chafetz, M. E., &amp; Wolf, I. (1967). The doctor’s voice: Postdictor of successful referral of alcoholic patients.&#160;<span className="Italic">Journal of Abnormal Psychology</span>,&#160;<span className="Italic">72</span>(1), 78–84. <a href="https://doi.org/10.1037/h0024219"><span className="Hyperlink">https://doi.org/10.1037/h0024219</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Ambady, N., Laplante, D., Nguyen, T., Rosenthal, R., Chaumeton, N., &amp; Levinson, W. (2002). Surgeons’ tone of voice: A clue to malpractice history. <span className="Italic">Surgery, 132</span>(1), 5–9. <a href="https://doi.org/10.1067/msy.2002.124733"><span className="Hyperlink">https://doi.org/10.1067/msy.2002.124733</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Colorcom. (n.d.). <span className="Italic">Why color matters</span>. CCICOLOR – Institute for Color Research. <a href="https://www.colorcom.com/research/why-color-matters"><span className="Hyperlink">https://www.colorcom.com/research/why-color-matters</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Fontaine, K., Briggs, L., &amp; Pope-Smith, B. (2001). Designing humanistic critical environments. <span className="Italic">Critical Care Nursing Quarterly, 24</span>(3), 21–34. <a href="https://doi.org/10.1097/00002727-200111000-00003"><span className="Hyperlink">https://doi.org/10.1097/00002727-200111000-00003</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Fast, J. (1970). <span className="Italic">Body language</span>. Simon &amp; Schuster.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Harlow, H. F., Dodsworth, R. O., &amp; Harlow, M. K. (1965). Total social isolation in monkeys. <span className="Italic">Proceedings of the National Academy of Sciences of the United States of America, 54</span>(1), 90–97. <a href="https://doi.org/10.1073/pnas.54.1.90"><span className="Hyperlink">https://doi.org/10.1073/pnas.54.1.90</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Hall, J. A., Harrigan, J. A., &amp; Rosenthal, R. (1995). Nonverbal behavior in clinician-patient interaction. <span className="Italic">Applied and Preventive Psychology, 4</span>(1), 21–37. <a href="https://doi.org/10.1016/S0962-1849(05)80049-6"><span className="Hyperlink">https://doi.org/10.1016/S0962-1849(05)80049-6</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">DiMatteo, M. R., Hays, R. D., &amp; Prince, L. M. (1986). Relationship of physicians’ nonverbal communication skill to patient satisfaction, appointment noncompliance, and physician workload. <span className="Italic">Health Psychology, 5</span>(6), 581–594. <a href="https://doi.org/10.1037/0278-6133.5.6.581"><span className="Hyperlink">https://doi.org/10.1037/0278-6133.5.6.581</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Friedman, H. S., DiMatteo, M. R., &amp; Taranta, A. (1980). A study of the relationship between individual differences in nonverbal expressiveness and factors in personality and social interaction. <span className="Italic">Journal of Research in Personality, 14</span>(3), 351–364.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Ruben, M. A., Blanch-Hartigan, D., &amp; Hall, J. A. (2016). Nonverbal communication as a pain reliever: The impact of physician supportive nonverbal behavior on experimentally induced pain. <span className="Italic">Health Communication, 31</span>(6), 1–7. <a href="https://doi.org/10.1080/10410236.2016.1196418"><span className="Hyperlink">https://doi.org/10.1080/10410236.2016.1196418</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Montague, E., &amp; Asan, O. (2012). Physician interactions with electronic health records in primary care.&#160;<span className="Italic">Health Systems (Basingstoke, England)</span>,&#160;<span className="Italic">1</span>(2), 96–103. <a href="https://doi.org/10.1057/hs.2012.11"><span className="Hyperlink">https://doi.org/10.1057/hs.2012.11</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 4</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Verbal Communication Styles: The Role of Assertiveness in Healthcare&#160;Communication</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Smith, M. J. (1975). <span className="Italic">When I say no, I feel guilty</span>. New York: Bantam.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Hunt, E. A., Shilkofski, N. A., Stavroudis, T. A., &amp; Nelson, K. L. (2007). Simulation: Translation to improved team performance. <span className="Italic">Anesthesiology Clinics, 25</span>(2), 301–319.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Attree, M. (2007). Factors influencing nurses’ decisions to raise concerns about care quality. <span className="Italic">Journal of Nursing Management, 15</span>(4), 392–402.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">O’Daniel, M., &amp; Rosenstein, A. H. (2008). Professional communication and team collaboration. In R. G. Hughes (Ed.), <span className="Italic">Patient safety and quality: An evidence-based handbook for nurses</span>. Agency for Healthcare Research and Quality.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Arnold, E., &amp; Boggs, K. U. (2019). <span className="Italic">Interpersonal relationships: Professional communication skills for nurses</span>. Elsevier.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Rajgopal, T., &amp; Singh, S. (2021). Communication challenges in Indian healthcare: A qualitative exploration. <span className="Italic">Journal of Family Medicine and Primary Care, 10</span>(2), 719–724.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Sharma, R., &amp; Rao, G. (2020). Patient communication and personality: A challenge for Indian primary care physicians. <span className="Italic">Indian Journal of Psychological Medicine, 42</span>(4), 371–376.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Thomas, V. A., &amp; Joseph, R. (2023). Personality traits and team communication in Indian healthcare professionals: A cross-sectional study. <span className="Italic">Journal of Healthcare Communication, 8</span>(2), 91–98.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Back, A. L., Arnold, R. M., &amp; Tulsky, J. A. (2009). <span className="Italic">Mastering communication with seriously ill patients: Balancing honesty with empathy and hope</span>. Cambridge University Press.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Petrucka, P. M., Bassendowski, S. L., &amp; Bajnok, I. (2021). A literature-based study of patient-centered care and communication in nurse–patient interactions. <span className="Italic">BMC Nursing, 20</span>, Article 158. <a href="https://doi.org/10.1186/s12912-021-00684-2"><span className="Hyperlink">https://doi.org/10.1186/s12912-021-00684-2</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Baile, W. F., Buckman, R., Lenzi, R., Glober, G., Beale, E. A., &amp; Kudelka, A. P. (2000). SPIKES—A six-step protocol for delivering bad news: Application to the patient with cancer. <span className="Italic">The Oncologist, 5</span>(4), 302–311. <a href="https://doi.org/10.1634/theoncologist.5-4-302"><span className="Hyperlink">https://doi.org/10.1634/theoncologist.5-4-302</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Silverman, J., Kurtz, S., &amp; Draper, J. (2013). <span className="Italic">Skills for communicating with patients</span> (3rd ed.). Radcliffe Publishing.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Sharkiya, S. (2023). Quality communication can improve patient-centred health outcomes among older patients: A rapid review. <span className="Italic">BMC Health Services Research, 23</span>, Article 886. <a href="https://doi.org/10.1186/s12913-023-09869-8"><span className="Hyperlink">https://doi.org/10.1186/s12913-023-09869-8</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Humphries, C., Jaganathan, S., Panniyammakal, J., Singh, S. K., Goenka, S., &amp; Manaseki-Holland, S. (2019). Patient and healthcare provider knowledge, attitudes and barriers to handover and healthcare communication during chronic disease inpatient care in India: A qualitative exploratory study. <span className="Italic">BMJ Open, 9</span>(11), e028199. <a href="https://doi.org/10.1136/bmjopen-2018-028199"><span className="Hyperlink">https://doi.org/10.1136/bmjopen-2018-028199</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 5</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Removing Communication Barriers in Hospital Settings: Bridging the Gap</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Ardalan, F., Valiee, S., &amp; others. (2018). Barriers of nurse-patient communication from the nurses’ point of view in educational hospitals affiliated to Kurdistan University of Medical Sciences. <span className="Italic">Nursing Practice Today, 5</span>(2), 290–298.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Alliance of Community Health Plans Foundation. (2007). <span className="Italic">Making the business case for culturally and linguistically appropriate services in healthcare: Case studies from the field</span> [PDF]. U.S. Department of Health and Human Services, Office of Minority Health. <a href="https://www.geneticcounselingtoolkit.com/pdf_files/CLAS%20Business%20Case.pdf"><span className="Hyperlink">https://www.geneticcounselingtoolkit.com/pdf_files/CLAS%20Business%20Case.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Tyson, P. (2012). <span className="Italic">The Hippocratic oath today</span>. PBS. <a href="http://www.pbs.org/wgbh/nova/body/hippocratic-oath-today.html"><span className="Hyperlink">http://www.pbs.org/wgbh/nova/body/hippocratic-oath-today.html</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">O’Toole, G. (2012). <span className="Italic">Communication: Core interpersonal skills for health professionals</span> (2nd ed.). Elsevier.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Silverman, J., Kurtz, S., &amp; Draper, J. (2013). <span className="Italic">Skills for communicating with patients</span> (3rd ed.). CRC Press.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Rao, H., Mahadevappa, H., Pillay, P., &amp; others. (2009). A qualitative study of patient-centred communication in mental health care. <span className="Italic">Psychiatric Quarterly, 80</span>(2), 125–137.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">National Institute on Deafness and Other Communication Disorders. (2022). <span className="Italic">Communication strategies for people with hearing loss</span>. U.S. Department of Health and Human Services. </li>
                        <li className="Ref ParaOverride-1" lang="en-US">World Health Organization. (2019). <span className="Italic">World report on vision</span>. WHO. <a href="https://www.who.int/publications/i/item/world-report-on-vision"><span className="Hyperlink">https://www.who.int/publications/i/item/world-report-on-vision</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Campos-Castillo, C., &amp; Anthony, D. L. (2021). Racial and ethnic differences in self-reported telehealth use during the COVID-19 pandemic. <span className="Italic">Health Affairs, 40</span>(2), 273–280.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Diamond, L. C., Izquierdo, K., Canfield, D., &amp; Matsoukas, K. (2019). A systematic review of the quality of translation and interpretation in health care. <span className="Italic">Medical Care, 57</span>(3), 217–224.</li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 6</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Managing Patient Expectations: The Art of Sensitivity</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Fuscaldo, D. (2007, August). <span className="Italic">What patients want, expect from health care providers</span>. Fox Business. <a href="https://www.foxbusiness.com/features/what-patients-want-expect-from-health-care-providers"><span className="Hyperlink">https://www.foxbusiness.com/features/what-patients-want-expect-from-health-care-providers</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">What is the Kano model? (n.d.). <span className="Italic">Kano Model</span>. <a href="https://www.kanomodel.com"><span className="Hyperlink">https://www.kanomodel.com</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Hahn, S. R., Kroenke, K., Spitzer, R. L., et al. (1996). The difficult patient: Prevalence, psychopathology, and functional impairment. <span className="Italic">Journal of General Internal Medicine, 11</span>(1), 1–8. <a href="https://doi.org/10.1007/BF02603477"><span className="Hyperlink">https://doi.org/10.1007/BF02603477</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Groves, J. E. (1978). Taking care of the hateful patient. <span className="Italic">The New England Journal of Medicine, 298</span>(16), 883–887. <a href="https://doi.org/10.1056/NEJM197804202981605"><span className="Hyperlink">https://doi.org/10.1056/NEJM197804202981605</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Lateef, F. (2011). Patient expectations and the paradigm shift of care in emergency medicine. <span className="Italic">Journal of Emergencies, Trauma, and Shock, 4</span>(2), 163–167. <a href="https://doi.org/10.4103/0974-2700.82199"><span className="Hyperlink">https://doi.org/10.4103/0974-2700.82199</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Large, A. (2020). Managing patient expectations. <span className="Italic">BDJ Team, 7</span>, 31. <a href="https://doi.org/10.1038/s41407-020-0431-9"><span className="Hyperlink">https://doi.org/10.1038/s41407-020-0431-9</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Bowman, D., &amp; Cushing, A. (2021). Ethical practice and clinical communication. In A. Feather, D. Randall, &amp; M. Waterhouse (Eds.), <span className="Italic">Kumar and Clark’s clinical medicine</span> (10th ed., chap. 5). Elsevier.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Nurse Magic. (n.d.). <span className="Italic">How to manage patient expectations and reduce frustration</span>. <a href="https://www.nursemagic.ai/post/how-to-manage-patient-expectations-and-reduce-frustration"><span className="Hyperlink">https://www.nursemagic.ai/post/how-to-manage-patient-expectations-and-reduce-frustration</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Deming, W. E. (1986). Drastic changes for western management. <span className="Italic">Meeting of the TIMS/ORS</span>, Australia. <a href="https://deming.org/wp-content/uploads/2020/06/Drastic-Changes-for-Western-Management-1986.pdf"><span className="Hyperlink">https://deming.org/wp-content/uploads/2020/06/Drastic-Changes-for-Western-Management-1986.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Right Now Technologies. (2010). <span className="Italic">Customer experience impact report</span>. <a href="https://www.slideshare.net/slideshow/2010-customer-experience-impact/5400618"><span className="Hyperlink">https://www.slideshare.net/slideshow/2010-customer-experience-impact/5400618</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Webber, A. E. (2008). <span className="Italic">B2B customer experience priorities in an economic downturn: Key customer usability initiatives in soft economy</span>. Forrester Research. <a href="https://www.forrester.com/report/B2B-Customer-Experience-Priorities-In-An-Economic-Downturn/RES41225"><span className="Hyperlink">https://www.forrester.com/report/B2B-Customer-Experience-Priorities-In-An-Economic-Downturn/RES41225</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Murphy, E. C., &amp; Murphy, M. A. (2002). <span className="Italic">Leading on the edge of chaos: The 10 critical elements for success in volatile times</span>. Prentice Hall. <a href="https://books.google.com.sg/books/about/Leading_on_the_edge_of_chaos.html?id=LOPtAAAAMAAJ"><span className="Hyperlink">https://books.google.com.sg/books/about/Leading_on_the_edge_of_chaos.html?id=LOPtAAAAMAAJ</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Mattarozzi, K., Sfrisi, F., Caniglia, F., De Palma, A., &amp; Martoni, M. (2017). What patients’ complaints and praise tell the health practitioner: Implications for health care quality. A qualitative research study. <span className="Italic">International Journal for Quality in Health Care, 29</span>(1), 83–89. <a href="https://doi.org/10.1093/intqhc/mzw139"><span className="Hyperlink">https://doi.org/10.1093/intqhc/mzw139</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 7</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Courtesy and Etiquette in Healthcare Communication: In the Spirit of Please and Thank You</span><span className="Bolditalic"> </span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Mayfield, E., Highfield, M. E. F., &amp; Mendelson, S. (2020).&#160;Meaning of courtesy and respect: Nurse and patient experiences. <span className="Italic">Journal of Nursing Care Quality</span>, 35(2), 177–181.&#160;<a href="https://doi.org/10.1097/NCQ.0000000000000424"><span className="Hyperlink">https://doi.org/10.1097/NCQ.0000000000000424</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Zachman, C. (2023). Getting back to courtesy and respect in healthcare.<span className="Italic"> The Beryl Institute. </span><a href="https://theberylinstitute.org/product/getting-back-to-courtesy-respect-in-healthcare/"><span className="Hyperlink">https://theberylinstitute.org/product/getting-back-to-courtesy-respect-in-healthcare/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Huron. (2022).&#160;<span className="Italic">AIDET communication framework</span>. <a href="https://www.huronconsultinggroup.com/insights/aidet-communication-framework"><span className="Hyperlink">https://www.huronconsultinggroup.com/insights/aidet-communication-framework</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Duffy, J. (2018).&#160;<span className="Italic">Quality caring in nursing and health systems: Implications for clinicians, educators and leaders</span>. Springer Publishing Company, NY.</li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 8</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Effective Communication in Nursing: The Healing Touch</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span> </p>
                    <ol>
                        <li className="RefF" lang="en-US">Benner, P. (1984).&#160;<span className="Italic">From novice to expert: Excellence and power in clinical nursing practice</span>. Addison-Wesley.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Strech, S., &amp; Wyatt, D. A. (2013). Partnering to lead change: Nurses’ role in the redesign of health care.&#160;<span className="Italic">AORN Journal, 98</span>(3), 260–266.&#160;<a href="https://doi.org/10.1016/j.aorn.2013.07.006"><span className="Hyperlink">https://doi.org/10.1016/j.aorn.2013.07.006</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">University of New Mexico. (n.d.). Importance of communication in nursing. <span className="Italic">RN BSN Online</span>.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Kourkouta, L., &amp; Papathanasiou, I. (2014). Communication in nursing practice. <span className="Italic">Materia Socio-Medica, 26</span>(1), 65. <a href="https://doi.org/10.5455/msm.2014.26.65-67"><span className="Hyperlink">https://doi.org/10.5455/msm.2014.26.65-67</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">McCabe, C. (2004). Nurse–patient communication: An exploration of patients’ experiences. <span className="Italic">Journal of Clinical Nursing, 13</span>(1), 41–49. <a href="https://doi.org/10.1111/j.1365-2702.2004.00817.x"><span className="Hyperlink">https://doi.org/10.1111/j.1365-2702.2004.00817.x</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Vertino, K. A. (2014). Effective interpersonal communication: A practical guide to improve your life. <span className="Italic">Online Journal of Issues in Nursing, 24</span>(3). <a href="https://doi.org/10.3912/OJIN.Vol19No03Man01"><span className="Hyperlink">https://doi.org/10.3912/OJIN.Vol19No03Man01</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 9</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Breaking Bad News to Patients and Their Relatives: Tread with Care</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Buckman, R., &amp; Kason, Y. (1992). <span className="Italic">Breaking bad news: A guide for healthcare professionals</span> (1st ed.). The Johns Hopkins University Press.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Harvey, P. (2010). <span className="Italic">Guidelines on the breaking of bad news</span> [PDF]. NHS. <a href="https://piel-l.org/blog/wp-content/uploads/2011/07/comunicacion-de-malas-noticias.pdf"><span className="Hyperlink">https://piel-l.org/blog/wp-content/uploads/2011/07/comunicacion-de-malas-noticias.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Baile, W. F., Buckman, R., Lenzi, R., Glober, G., Beale, E. A., &amp; Kudelka, A. P. (2000). SPIKES: A six-step protocol for delivering bad news: Application to the patient with cancer. <span className="Italic">Oncologist, 5</span>(4), 302–311. <a href="https://doi.org/10.1634/theoncologist.5-4-302"><span className="Hyperlink">https://doi.org/10.1634/theoncologist.5-4-302</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Rabow, M. W., &amp; McPhee, S. J. (1999). Beyond breaking bad news: How to help patients who suffer. <span className="Italic">Western Journal of Medicine, 171</span>(4), 260–263.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Shah, P., Thornton, I., Kopitnik, N. L., et al. (2025). Informed consent. StatPearls Publishing. <a href="https://www.ncbi.nlm.nih.gov/books/NBK430827/"><span className="Hyperlink">https://www.ncbi.nlm.nih.gov/books/NBK430827/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Medical Council of India. (2002). <span className="Italic">Code of Ethics Regulations 2002</span> (Published in Part III, Section 4 of the Gazette of India). <a href="https://www.nmc.org.in/rules-regulations/code-of-medical-ethics-regulations-2002/"><span className="Hyperlink">https://www.nmc.org.in/rules-regulations/code-of-medical-ethics-regulations-2002/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Kurer, M. A., &amp; Zekri, J. M. (2008). Breaking bad news: Can we get it right? <span className="Italic">Libyan Journal of Medicine, 3</span>(4), 200–203. <a href="https://doi.org/10.4176/080825"><span className="Hyperlink">https://doi.org/10.4176/080825</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Yousuf, A. A. A. A., Stewart, D. C., Kane, T., Soltani, A., Al-Khal, A., &amp; Sethi, A. (2024). Health professionals’ views and experiences of breaking bad news in the Eastern Mediterranean Region: A scoping review. <span className="Italic">Frontiers in Medicine, 11,</span> 1440867. <a href="https://doi.org/10.3389/fmed.2024.1440867"><span className="Hyperlink">https://doi.org/10.3389/fmed.2024.1440867</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 10</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">The Disclosure of Medical Errors: “Sorry” Works</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Kohn, L. T., Corrigan, J., &amp; Donaldson, M. S. (2000). <span className="Italic">To err is human: Building a safer health system</span>. Institute of Medicine, Washington, DC: National Academy Press.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">American Medical Association. (2012). <span className="Italic">Code of medical ethics: Current opinions with annotations, 2012–2013</span> [Online]. </li>
                        <li className="Ref ParaOverride-1" lang="en-US">Gallagher, T. H., &amp; Levinson, W. (2005). Disclosing harmful medical errors to patients: A time for professional action. <span className="Italic">Archives of Internal Medicine, 165</span>(16), 1819–1823. <a href="https://doi.org/10.1001/archinte.165.16.1819"><span className="Hyperlink">https://doi.org/10.1001/archinte.165.16.1819</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Gallagher, T. H., Waterman, A. D., Ebers, A. G., Fraser, V. J., &amp; Levinson, W. (2003). Patients’ and physicians’ attitudes regarding the disclosure of medical errors. <span className="Italic">JAMA, 289</span>(8), 1001–1007. <a href="https://doi.org/10.1001/jama.289.8.1001"><span className="Hyperlink">https://doi.org/10.1001/jama.289.8.1001</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Banja, J. (2005). <span className="Italic">Medical errors and medical narcissism</span>. Burlington, MA. Jones and Bartlett.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">World Health Organization. (2024). <span className="Italic">Global patient safety report 2024</span>. World Health Organization. <a href="https://www.who.int/publications/i/item/9789240095458"><span className="Hyperlink">https://www.who.int/publications/i/item/9789240095458</span></a></li>
                    </ol>
                    <p className="H2-copy" lang="en-US"><span className="Bold">ADDITIONAL RESOURCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Agency for Healthcare Research and Quality (AHRQ) CANDOR Toolkit: <a href="https://www.ahrq.gov/patient-safety/settings/hospital/candor/index.html"><span className="Hyperlink">https://www.ahrq.gov/patient-safety/settings/hospital/candor/index.html</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">National Health Service Duty of Candour Toolkit: <a href="https://nhssomerset.nhs.uk/wp-content/uploads/sites/2/DoC-Toolkit.pdf"><span className="Hyperlink">https://nhssomerset.nhs.uk/wp-content/uploads/sites/2/DoC-Toolkit.pdf</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 11</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Unacceptable Communication: Knowing Where to Draw the Line</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Lind, P. (2012). <span className="Italic">Setting up behavioral expectations for your clinic</span> [PDF]. <a href="http://pattilind.com/documents/behavioralexpectations.pdf"><span className="Hyperlink">http://pattilind.com/documents/behavioralexpectations.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">CARE Emergency Toolkit. (2019). Guidance note: Feedback and complaints mechanism. <a href="https://www.careemergencytoolkit.org/wp-content/uploads/2019/09/2019-06-CARE-FCM-Guidance.pdf"><span className="Hyperlink">https://www.careemergencytoolkit.org/wp-content/uploads/2019/09/2019-06-CARE-FCM-Guidance.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">VELA. (2024). Feedback and accountability policy. <a href="https://vela.ngo/wp-content/uploads/2024/03/VELA-FEEDBACK-AND-ACCOUNTABILITY-POLICY.pdf"><span className="Hyperlink">https://vela.ngo/wp-content/uploads/2024/03/VELA-FEEDBACK-AND-ACCOUNTABILITY-POLICY.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Khan, C. (2020). Accountability, feedback &amp; complaints mechanisms in humanitarian responses to migration. Start Network. <a href="https://www.ready-initiative.org/wp-content/uploads/2021/03/Start-Network_-Feedback-and-Complaints-in-MM-learning-piece_Final.pdf"><span className="Hyperlink">https://www.ready-initiative.org/wp-content/uploads/2021/03/Start-Network_-Feedback-and-Complaints-in-MM-learning-piece_Final.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Akarsu, E. (2020). 12 steps to a great online feedback and complaints mechanism. <a href="https://accountablenow.org/insights/12-steps-to-a-great-online-feedback-and-complaints-mechanism/"><span className="Hyperlink">https://accountablenow.org/insights/12-steps-to-a-great-online-feedback-and-complaints-mechanism/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">BMC. (2024). Feedback mechanisms at work: HRM strategies to boost performance and engagement. <a href="https://www.bmc.net/blog/general-blog-posts/feedback-mechanisms-in-hrm"><span className="Hyperlink">https://www.bmc.net/blog/general-blog-posts/feedback-mechanisms-in-hrm</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">The Hindu. (2024, Nov. 17). 35 doctors in India feel unsafe while at work, survey shows. <a href="https://www.thehindu.com/news/national/35-doctors-in-india-feel-unsafe-while-at-work-survey-shows/article68872488.ece"><span className="Hyperlink">https://www.thehindu.com/news/national/35-doctors-in-india-feel-unsafe-while-at-work-survey-shows/article68872488.ece</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">O’Brien, C. J., van Zundert, A. A. J., &amp; Barach, P. R. (2024). The growing burden of workplace violence against healthcare workers: Trends in prevalence, risk factors, consequences, and prevention – A narrative review. <span className="Italic">eClinicalMedicine, 72</span>, 102641. <a href="https://doi.org/10.1016/j.eclinm.2024.102641"><span className="Hyperlink">https://doi.org/10.1016/j.eclinm.2024.102641</span></a></li>
                    </ol>
                    <p className="H2-copy" lang="en-US"><span className="Bold">ADDITIONAL RESOURCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">[Book] <span className="Italic">Perils in Practice: Prevention of Violence Against Healthcare Professionals</span> by Alexander Thomas, Sahajanand Prasad Singh and Divya Alexander. <a href="https://southshore.in/api/uploads/openaccess/pdfs/11.pdf"><span className="Hyperlink">https://southshore.in/api/uploads/openaccess/pdfs/11.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">[Toolkit] Occupational Hazards in the Health Sector: Violence and Harassment by the World Health Organisation. <a href="https://www.who.int/tools/occupational-hazards-in-health-sector/violence-harassment"><span className="Hyperlink">https://www.who.int/tools/occupational-hazards-in-health-sector/violence-harassment</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 12</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Communication with Diverse Patient Groups: Enhancing Care Through&#160;Inclusivity</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Ernstmeyer, K., &amp; Christman, E. (Eds.). (2022). <span className="Italic">Nursing: Mental health and community concepts</span> (Chap. 17, Vulnerable Populations). Open Resources for Nursing (Open RN), Chippewa Valley Technical College. <a href="https://www.ncbi.nlm.nih.gov/books/NBK590046/"><span className="Hyperlink">https://www.ncbi.nlm.nih.gov/books/NBK590046/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Ahrens, E., &amp; Elias, M. (2023). Effective communication with linguistically diverse patients: A concept analysis. <span className="Italic">Patient Education and Counseling, 115,</span> 107868. <a href="https://doi.org/10.1016/j.pec.2023.107868"><span className="Hyperlink">https://doi.org/10.1016/j.pec.2023.107868</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Sudhinaraset, M., Treleaven, E., Melo, J., Singh, K., &amp; Diamond-Smith, N. (2016). Women’s status and experiences of mistreatment during childbirth in Uttar Pradesh: A mixed methods study using cultural health capital theory. <span className="Italic">BMC Pregnancy and Childbirth, 16,</span> 332. <a href="https://doi.org/10.1186/s12884-016-1124-4"><span className="Hyperlink">https://doi.org/10.1186/s12884-016-1124-4</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Levin, S. J., Like, R. C., &amp; Gottlieb, J. E. (1997). <span className="Italic">Communicating with diverse people.</span> Center for Healthy Families and Cultural Diversity, Department of Family Medicine, UMDNJ-Robert Wood Johnson Medical School. <a href="https://www.champlainscreen.ca/wp-content/uploads/2014/03/Communicating_with_diverse_People.pdf"><span className="Hyperlink">https://www.champlainscreen.ca/wp-content/uploads/2014/03/Communicating_with_diverse_People.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Govere, L., &amp; Govere, E. M. (2016). How effective is cultural competence training of healthcare providers on improving patient satisfaction of minority groups? A systematic review of literature. <span className="Italic">Worldviews on Evidence-Based Nursing, 13</span>(6), 402–410. <a href="https://doi.org/10.1111/wvn.12176"><span className="Hyperlink">https://doi.org/10.1111/wvn.12176</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Garcia Valencia, O. A., Thongprayoon, C., Jadlowiec, C. C., Mao, S. A., Leeaphorn, N., Budhiraja, P., Craici, I. M., Gonzalez Suarez, M. L., &amp; Cheungpasitporn, W. (2024). AI-driven translations for kidney transplant equity in Hispanic populations. <span className="Italic">Scientific Reports, 14</span>(1), 8511. <a href="https://doi.org/10.1038/s41598-024-59237-7"><span className="Hyperlink">https://doi.org/10.1038/s41598-024-59237-7</span></a></li>
                    </ol>
                    <p className="H2-copy" lang="en-US"><span className="Bold">ADDITIONAL RESOURCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">[Toolkit] Caring for diverse populations. Better communication, better care: A toolkit for physicians and health care professionals by Amerigroup. <a href="https://provider.amerigroup.com/docs/gpp/NM_CulturalCompetencyToolkit.pdf?v=202102040134"><span className="Hyperlink">https://provider.amerigroup.com/docs/gpp/NM_CulturalCompetencyToolkit.pdf?v=202102040134</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">[Book] <span className="Italic">Fundamentals of Clinical Communication: A Step-by-Step Guide for Medical Students</span> by Indu Arneja and Pawanindra Lal</li>
                        <li className="Ref ParaOverride-1" lang="en-US">[Book] <span className="Italic">The Care of Vulnerable Older People: Legal and Ethical Aspects of Nursing</span> by Paul Buka, Monica Davis and Madalene Pereira</li>
                        <li className="Ref ParaOverride-1" lang="en-US">[Book] <span className="Italic">The Future of Healthcare: Transforming with Technology </span>edited by Alexander Thomas, S. Raghunath, Divya Alexander and Sandeep Bhalla</li>
                        <li className="Ref ParaOverride-1" lang="en-US">[Book] <span className="Italic">Embracing the Golden Years: A Guide to Happy and Healthy Ageing </span>edited by Alexander Thomas, Kris Gopalakrishnan, Divya Alexander and Sugandhi Baliga</li>
                        <li className="Ref ParaOverride-1" lang="en-US">[Article] How can healthcare professionals effectively communicate with diverse patients? LinkedIn. <a href="https://www.linkedin.com/advice/3/how-can-healthcare-professionals-effectively"><span className="Hyperlink">https://www.linkedin.com/advice/3/how-can-healthcare-professionals-effectively</span></a></li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 13</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Health Literacy and Patient Education: Empowering Through Engagement</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">World Health Organization. (2023). <span className="Italic">Patient safety</span> [Fact sheet]. <a href="https://www.who.int/news-room/fact-sheets/detail/patient-safety"><span className="Hyperlink">https://www.who.int/news-room/fact-sheets/detail/patient-safety</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Shahid, R., Shoker, M., Chu, L. M., Frehlick, R., Ward, H., &amp; Pahwa, P. (2022). Impact of low health literacy on patients’ health outcomes: A multicenter cohort study. <span className="Italic">BMC Health Services Research, 22</span>(1), 1148. <a href="https://doi.org/10.1186/s12913-022-08527-9"><span className="Hyperlink">https://doi.org/10.1186/s12913-022-08527-9</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Kim, Y. S., Kim, H. S., Kim, H. A., Chun, J., Kwak, M. J., Kim, M. S., Hwang, J. I., &amp; Kim, H. (2020). Can patient and family education prevent medical errors? A descriptive study. <span className="Italic">BMC Health Services Research, 20</span>(1), 269. <a href="https://doi.org/10.1186/s12913-020-05083-y"><span className="Hyperlink">https://doi.org/10.1186/s12913-020-05083-y</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Guideway Care. (2025). <span className="Italic">Understanding the link between health literacy and patient </span><span className="Italic">satisfaction?</span> <a href="https://guidewaycare.com/understanding-whats-the-link-between-health-literacy-and-patient-satisfaction/"><span className="Hyperlink">https://guidewaycare.com/understanding-whats-the-link-between-</span><span className="Hyperlink">health-literacy-and-patient-satisfaction/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Singh, H., Meyer, A. N., &amp; Thomas, E. J. (2014). The frequency of diagnostic errors in outpatient care: Estimations from three large observational studies involving U.S. adult populations. <span className="Italic">BMJ Quality &amp; Safety, 23</span>(8), 727–731. <a href="https://qualitysafety.bmj.com/content/qhc/23/9/727.full.pdf"><span className="Hyperlink">https://qualitysafety.bmj.com/content/qhc/23/9/727.full.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Schiff, G. D., Kim, S., Abrams, R., et al. (2005). Diagnosing diagnosis errors: Lessons from a multi-institutional collaborative project. In K. Henriksen, J. B. Battles, E. S. Marks, &amp; others (Eds.), <span className="Italic">Advances in patient safety: From research to implementation</span> (Volume 2: Concepts and methodology). Agency for Healthcare Research and Quality. <a href="https://www.ncbi.nlm.nih.gov/books/NBK20492/"><span className="Hyperlink">https://www.ncbi.nlm.nih.gov/books/NBK20492/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Wu, M.-J., Chen, C.-H., &amp; Tsai, S.-F. (2023). Effects of patient support group on health literacy: A study using the multidimensional health literacy questionnaire. <span className="Italic">Medicine, 102</span>(21), e33901. <a href="https://doi.org/10.1097/MD.0000000000033901"><span className="Hyperlink">https://doi.org/10.1097/MD.0000000000033901</span></a></li>
                    </ol>
                    <p className="H2-copy" lang="en-US"><span className="Bold">ADDITIONAL RESOURCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">[Toolkit] Engaging Patients to Enhance Patient Safety: A Comprehensive Toolkit for Healthcare Providers by CAHO (Consortium of Accredited Healthcare Organisations) and Patients for Patient Safety Foundation. <a href="https://patientsforpatientsafety.in/assets/pdf/Toolkit-Engaging-Patients-To-Enhance-Patient-A-Comprehensive-Toolkit-For-Healthcare-Providers.pdf"><span className="Hyperlink">https://patientsforpatientsafety.in/assets/pdf/Toolkit-Engaging-Patients-To-Enhance-Patient-A-Comprehensive-Toolkit-For-Healthcare-Providers.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">[Library Resource] Patients for Patient Safety Foundation Health Library <a href="https://www.patientsforpatientsafety.in/resources.php"><span className="Hyperlink">https://www.patientsforpatientsafety.in/resources.php</span></a></li>
                    </ol>
                    <p className="Basic-Paragraph ParaOverride-2" lang="en-US"><span className="Hyperlink"><img className="_idGenObjectAttribute-1" src="Reference_and_Resources-web-resources/image/Image129894.jpg" alt="" /></span></p>
                    <p className="H2" lang="en-US"><span className="Italic CharOverride-1">(Scan below to access the Patients for Patient Safety health library.)</span></p>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 14</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Communication Flow in Healthcare Organisations: Pathways and Processes</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">The Joint Commission. (2023). <span className="Italic">Sentinel event data root causes by event type.</span> <a href="https://www.jointcommission.org/resources/patient-safety-topics/sentinel-event/events-root-cause-analysis/"><span className="Hyperlink">https://www.jointcommission.org/resources/patient-safety-topics/sentinel-event/events-root-cause-analysis/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Sutcliffe, K. M., Lewton, E., &amp; Rosenthal, M. M. (2004). Communication failures: An insidious contributor to medical mishaps. <span className="Italic">Academic Medicine: Journal of the American Medical Colleges, 79</span>(2), 186–194. <a href="https://doi.org/10.1097/00001888-200402000-00019"><span className="Hyperlink">https://doi.org/10.1097/00001888-200402000-00019</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Leonard, M., Graham, S., &amp; Bonacum, D. (2004). The human factor: The critical importance of effective teamwork and communication in providing safe care. <span className="Italic">Quality &amp; Safety in Health Care, 13</span>(Suppl 1), i85–i90. <a href="https://doi.org/10.1136/qhc.13.suppl_1.i85"><span className="Hyperlink">https://doi.org/10.1136/qhc.13.suppl_1.i85</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Starmer, A. J., Spector, N. D., Srivastava, R., West, D. C., Rosenbluth, G., Allen, A. D., &amp; Noble, E. L. (2014). Changes in medical errors after implementation of a handoff program. <span className="Italic">New England Journal of Medicine, 371</span>(19), 1803–1812. <a href="https://doi.org/10.1056/NEJMsa1405556"><span className="Hyperlink">https://doi.org/10.1056/NEJMsa1405556</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Institute for Healthcare Improvement. (n.d.). <span className="Italic">SBAR technique for communication: A situational briefing model.</span> <a href="https://www.ihi.org/library/tools/sbar-tool-situation-background-assessment-recommendation"><span className="Hyperlink">https://www.ihi.org/library/tools/sbar-tool-situation-background-assessment-recommendation</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">O’Daniel, M., &amp; Rosenstein, A. H. (2008). Professional communication and team collaboration. In R. G. Hughes (Ed.), <span className="Italic">Patient safety and quality: An evidence-based handbook for nurses</span> (Chapter 33). Agency for Healthcare Research and Quality. <a href="https://www.ncbi.nlm.nih.gov/books/NBK2637/"><span className="Hyperlink">https://www.ncbi.nlm.nih.gov/books/NBK2637/</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Manser, T. (2009). Teamwork and patient safety in dynamic domains of healthcare: A review of the literature. <span className="Italic">Acta Anaesthesiologica Scandinavica, 53</span>(2), 143–151. <a href="https://doi.org/10.1111/j.1399-6576.2008.01717.x"><span className="Hyperlink">https://doi.org/10.1111/j.1399-6576.2008.01717.x</span></a></li>
                    </ol>
                    <p className="H2-copy" lang="en-US"><span className="Bold">ADDITIONAL RESOURCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">[Book] <span className="Italic">High Performance Healthcare: Using the Power of Relationships to Achieve Quality, Efficiency and Resilience</span> by J. H. Gittell</li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 15</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">Communication During Transition of Care: Passing the Torch</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">British Medical Association, National Patient Safety Agency &amp; NHS Modernisation Agency. (2005). <span className="Italic">Safe handover: Safe patients – Guidance on clinical handover for clinicians and managers</span>. <a href="https://www.rcpch.ac.uk/sites/default/files/2018-02/bma_handover_college_tutors.pdf"><span className="Hyperlink">https://www.rcpch.ac.uk/sites/default/files/2018-02/bma_handover_college_tutors.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Joint Commission International. (2018). <span className="Italic">Communicating clearly and effectively to patients: How to overcome common communication challenges in health care (White Paper)</span>. <a href="https://store.jointcommissioninternational.org/assets/3/7/jci-wp-communicating-clearly-final_(1).pdf"><span className="Hyperlink">https://store.jointcommissioninternational.org/assets/3/7/jci-wp-communicating-clearly-final_(1).pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Pezzolesi, C., Schifano, F., Pickles, J., Randell, W., Hussain, Z., Muir, H., &amp; Dhillon, S. (2010). Clinical handover incident reporting in one UK general hospital. <span className="Italic">International Journal for Quality in Health Care, 22</span>(5), 396–401. <a href="https://doi.org/10.1093/intqhc/mzq048"><span className="Hyperlink">https://doi.org/10.1093/intqhc/mzq048</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Australian Commission on Safety and Quality in Health Care. (2012). <span className="Italic">The OSSIE Guide to Clinical Handover Improvement. </span> <a href="https://www.safetyandquality.gov.au/sites/default/files/2019-12/ossie_guide_to_clinical_handover_improvement.pdf"><span className="Hyperlink">https://www.safetyandquality.gov.au/sites/default/files/2019-12/ossie_guide_to_clinical_handover_improvement.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Arora, V., Johnson, J., Lovinger, D., Humphrey, H. J., &amp; Meltzer, D. O. (2005). Communication failures in patient sign-out and suggestions for improvement: A critical incident analysis. <span className="Italic">Quality &amp; Safety in Health Care, 14</span>(6), 401–407. <a href="https://doi.org/10.1136/qshc.2005.015107"><span className="Hyperlink">https://doi.org/10.1136/qshc.2005.015107</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Horn, J., Bell, M. D., &amp; Moss, E. (2004). Handover of responsibility for the anaesthetised patient - opinion and practice.&#160;<span className="Italic">Anaesthesia</span>,&#160;<span className="Italic">59</span>(7), 658–663. <a href="https://doi.org/10.1111/j.1365-2044.2004.03760.x"><span className="Hyperlink">https://doi.org/10.1111/j.1365-2044.2004.03760.x</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Catchpole, K. R., de Leval, M. R., McEwan, A., Pigott, N., Elliott, M. J., McQuillan, A., MacDonald, C., &amp; Goldman, A. J. (2007). Patient handover from surgery to intensive care: Using Formula 1 pit-stop and aviation models to improve safety and quality. <span className="Italic">Paediatric Anaesthesia, 17</span>(5), 470–478. <a href="https://doi.org/10.1111/j.1460-9592.2006.02239.x"><span className="Hyperlink">https://doi.org/10.1111/j.1460-9592.2006.02239.x</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Riesenberg, L. A., Leitzsch, J., &amp; Little, B. W. (2019). Systematic review of handoff mnemonics literature. <span className="Italic">American Journal of Medical Quality, 34</span>(5), 446–454. <a href="https://doi.org/10.1177/1062860619873200"><span className="Hyperlink">https://doi.org/10.1177/1062860619873200</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Institute for Healthcare Improvement. (2016, April 13). Effective communication in healthcare: A guide to improving outcomes. </li>
                        <li className="Ref ParaOverride-1" lang="en-US">World Health Organization. (2007, May). <span className="Italic">Patient safety solutions (Vol. 1, Solution 3): Communication during patient hand-overs</span>. <a href="https://cdn.who.int/media/docs/default-source/patient-safety/patient-safety-solutions/ps-solution3-communication-during-patient-handovers.pdf"><span className="Hyperlink">https://cdn.who.int/media/docs/default-source/patient-safety/patient-safety-solutions/ps-solution3-communication-during-patient-handovers.pdf</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Curtis, K., Murphy, M., Hoy, S., &amp; Lewis, M. J. (2009). The emergency nursing assessment process: A structured framework for a systematic approach. <span className="Italic">Australasian Emergency Nursing Journal, 12</span>(4), 130–136. <a href="https://doi.org/10.1016/j.aenj.2009.07.003"><span className="Hyperlink">https://doi.org/10.1016/j.aenj.2009.07.003</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Pope, B. B., Rodzen, L., &amp; Spross, G. (2008). Raising the SBAR: How better communication improves patient outcomes. <span className="Italic">Nursing, 38</span>(3), 41–43. <a href="https://doi.org/10.1097/01.NURSE.0000312625.74434.e8"><span className="Hyperlink">https://doi.org/10.1097/01.NURSE.0000312625.74434.e8</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Joint Commission Center for Transforming Healthcare. (2013, May 13). Improving transitions of care: Hand-off communication (Targeted Solutions Tool update).</li>
                    </ol>
                    <p className="H1" lang="en-US"><span className="Bold">Chapter 16</span></p>
                    <p className="H2" lang="en-US"><span className="Bold">How Social Media is Revolutionising Healthcare Communication: From&#160;Clicks to Care</span></p>
                    <p className="H2-copy" lang="en-US"><span className="Bold">REFERENCES</span></p>
                    <ol>
                        <li className="RefF ParaOverride-1" lang="en-US">Lin, M., &amp; Kishore, R. (2021). Social media-enabled healthcare: A conceptual model of social media affordances, online social support, and health behaviors and outcomes, <span className="Italic">Technological Forecasting and Social Change, 166</span>,<span className="Italic"> </span>120574. <a href="https://doi.org/10.1016/j.techfore.2021.120574"><span className="Hyperlink">https://doi.org/10.1016/j.techfore.2021.120574</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Yan, Z., Wang, T., Chen, Y., &amp; Zhang, H. (2015). Knowledge sharing in online health communities: A social exchange theory perspective. <span className="Italic">Information &amp; Management, 53</span>(5), 643–659. <a href="https://doi.org/10.1016/j.im.2016.02.001"><span className="Hyperlink">https://doi.org/10.1016/j.im.2016.02.001</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Antheunis, M. L., Tates, K., &amp; Nieboer, T. E. (2013). Patients’ and health professionals’ use of social media in health care: Motives, barriers and expectations. <span className="Italic">Patient Education and Counseling, 92</span>(3), 426–431. <a href="https://doi.org/10.1016/j.pec.2013.06.020"><span className="Hyperlink">https://doi.org/10.1016/j.pec.2013.06.020</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Maloney-Krichmar, D., &amp; Preece, J. (2005). A multilevel analysis of sociability, usability, and community dynamics in an online health community. <span className="Italic">ACM Transactions on Computer-Human Interaction (TOCHI), 12</span>(2), 201–232. <a href="https://doi.org/10.1145/1067860.1067864"><span className="Hyperlink">https://doi.org/10.1145/1067860.1067864</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Xiao, N., Sharman, R., Rao, H. R., &amp; Upadhyaya, S. (2014). Factors influencing online health information search: An empirical analysis of a national cancer-related survey. <span className="Italic">Decision Support Systems, 57</span>, 417–427. <a href="https://doi.org/10.1016/j.dss.2012.10.047"><span className="Hyperlink">https://doi.org/10.1016/j.dss.2012.10.047</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Yan, Z., &amp; Tan, Y. (2014). Feeling blue? Go online: An empirical study of social support among patients. <span className="Italic">Information Systems Research, 25</span>(4), 690–709. <a href="https://doi.org/10.1287/isre.2014.0538"><span className="Hyperlink">https://doi.org/10.1287/isre.2014.0538</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Von Muhlen, M., &amp; Ohno-Machado, L. (2012). Reviewing social media use by clinicians. <span className="Italic">Journal of the American Medical Informatics Association, 19</span>(5), 777–781. <a href="https://doi.org/10.1136/amiajnl-2012-000990"><span className="Hyperlink">https://doi.org/10.1136/amiajnl-2012-000990</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Merolli, M., Gray, K., &amp; Martin-Sanchez, F. (2013). Health outcomes and related effects of using social media in chronic disease management: A literature review and analysis of affordances. <span className="Italic">Journal of Biomedical Informatics, 46</span>(6), 957–969. <a href="https://doi.org/10.1016/j.jbi.2013.04.010"><span className="Hyperlink">https://doi.org/10.1016/j.jbi.2013.04.010</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Berkman, L. F., Glass, T., Brissette, I., &amp; Seeman, T. E. (2000). From social integration to health: Durkheim in the new millennium. <span className="Italic">Social Science &amp; Medicine, 51</span>(6), 843–857. <a href="https://doi.org/10.1016/S0277-9536(00)00065-4"><span className="Hyperlink">https://doi.org/10.1016/S0277-9536(00)00065-4</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">House, J. S. (1981). <span className="Italic">Work stress and social support</span>. Addison-Wesley.</li>
                        <li className="Ref ParaOverride-1" lang="en-US">Uchino, B. N. (2006). Social support and health: A review of physiological processes potentially underlying links to disease outcomes. <span className="Italic">Journal of Behavioral Medicine, 29</span>(4), 377–387. <a href="https://doi.org/10.1007/s10865-006-9056-5"><span className="Hyperlink">https://doi.org/10.1007/s10865-006-9056-5</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Uchino, B. N. (2009). Understanding the links between social support and physical health: A lifespan perspective with emphasis on the separability of perceived and received support. <span className="Italic">Perspectives on Psychological Science, 4</span>(3), 236–255. <a href="https://doi.org/10.1111/j.1745-6924.2009.01122.x"><span className="Hyperlink">https://doi.org/10.1111/j.1745-6924.2009.01122.x</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Fichman, R. G., Kohli, R., &amp; Krishnan, R. (2011). The role of information systems in healthcare: Current research and future trends. <span className="Italic">Information Systems Research, 22</span>(3), 419–428. <a href="https://doi.org/10.1287/isre.1110.0382"><span className="Hyperlink">https://doi.org/10.1287/isre.1110.0382</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Markus, M. L., &amp; Silver, M. S. (2008). A foundation for the study of IT effects: A new look at DeSanctis and Poole’s concepts of structural features and spirit. <span className="Italic">Journal of the Association for Information Systems, 9</span>(10), 609–632. <a href="https://doi.org/10.17705/1jais.00176"><span className="Hyperlink">https://doi.org/10.17705/1jais.00176</span></a></li>
                        <li className="Ref ParaOverride-1" lang="en-US">Telecom Regulatory Authority of India. (2023, September 14). <span className="Italic">Consultation paper on digital inclusion in the era of emerging technologies</span>. </li>
                    </ol>
                </div>
                <div id="_idContainer002" className="Basic-Text-Frame">
                    <p className="CT" lang="en-US">References and RESOURCES</p>
                </div>
            </div>
            <FooterSouthsore />

        </>
    )
}

export default References
